"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

import setuptools

try:
    with open("README.md", "r") as fh:
        long_description = fh.read()
except FileNotFoundError:
    long_description = ""

setuptools.setup(
    name="calendly-py",
    version="0.0.2",
    author="Speakeasy",
    description="Python SDK for the calendly API Generated by Speakeasy",
    long_description=long_description,
    long_description_content_type="text/markdown",
    packages=setuptools.find_packages(where="src"),
    install_requires=[
        "certifi==2022.12.07",
        "charset-normalizer==2.1.1",
        "dataclasses-json-speakeasy==0.5.8",
        "idna==3.3",
        "marshmallow==3.17.1",
        "marshmallow-enum==1.5.1",
        "mypy-extensions==0.4.3",
        "packaging==24.0",
        "pyparsing==3.2.5",
        "python-dateutil==2.8.2",
        "requests==2.32.5",
        "six==1.17.0",
        "typing-inspect==0.8.0",
        "typing_extensions==4.5.0",
        "urllib3==2.0.7",
        "pylint==2.16.2",
    ],
    package_dir={'': 'src'},
    python_requires='>=3.9'
)
